### ISSUE TITLE
Copyleft licensing

### ISSUE THREAD

**Issue by wesm** [powturbo/Turbo-Run-Length-Encoding#8]
I have noticed that you use GPLv2 in some of your repositories, such as this one. This prevents code reuse in permissively licensed open source projects. I wanted to check if this is your intent, and, if so, if you would be willing to choose a permissive license such as Apache 2.0.

**Comment by magenbluten** [comment]
Or at least LGPL. That GPL* turned out to be a show stopper in my case ( contractor refused )

**Comment by wesm** [comment]
Note that LGPL is on the Category X list for Apache Software Foundation projects

https://www.apache.org/legal/resolved.html#category-x

**Comment by powturbo** [comment]
Actually, there are no plan to change the license
